FROM theasp/fluentd-plugins:certified

ENV BUILD_DEPS="jq curl make gcc g++ rake patch libc-dev ruby-dev zlib1g-dev libcurl4-openssl-dev libpq-dev libssl-dev libsqlite3-dev default-libmysqlclient-dev libgeoip-dev libsasl2-dev libxml2-dev libffi-dev libmaxminddb-dev"

RUN set -ex; \
   apt-get update -q; \
   apt-cache search '.*mysql.*-dev' ; \
   apt-get install -qy --no-install-recommends $BUILD_DEPS; \
   curl -s https://www.fluentd.org/plugins \
     | grep '^  var plugins' \
     | cut -f 2- -d = \
     | sed -e 's/;$//' \
     | jq -r 'map(select(.obsolete != true and (.downloads > 20000 or (.certified|length) > 0))) | .[].name | @text' > /tmp/plugins-slim; \
   test -s /tmp/plugins-slim; \
   xargs -r gem install < /tmp/plugins-slim; \
   sort -u /plugins-installed /tmp/plugins-slim > /plugins-installed.new; \
   mv /plugins-installed.new /plugins-installed; \
   gem sources --clear-all; \
   apt-get purge -qy $(dpkg-query --show --showformat '${Package}\n' '*-dev'); \
   rm -rf /var/lib/apt/lists/* /home/fluent/.gem/ruby/*/cache/*.gem /tmp/plugins-slim
