FROM fluent/fluentd:edge-debian

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish

ENV BUILD_DEPS="sudo make gcc g++ rake patch libc-dev ruby-dev zlib1g-dev libcurl4-openssl-dev libpq-dev libssl-dev libsqlite3-dev default-libmysqlclient-dev libgeoip-dev libsasl2-dev libxml2-dev"

ENV PLUGINS=" \
add \
amazon_sns \
anonymizer \
assert \
aws-elasticsearch-service \
bigquery \
cloudwatch \
cloudwatch_ya \
collectd-influxdb \
concat \
couch \
datacalculator \
dedot_filter \
docker-format \
docker-journald-concat \
docker_metadata_filter \
dynamodb \
elasticsearch \
elasticsearch-timestamp-check \
elb-access-log \
elb-log \
esslowquery \
eval-filter \
fields-parser \
filter \
filter_typecast \
forward-aws \
gcloud-pubsub-custom \
geoip \
google-cloud \
graphite \
grep \
grok-parser \
growthforecast \
hipchat \
ignore-filter \
ikachan \
influxdb \
irc \
json-in-json \
json-nest2flat \
json-parser \
kinesis \
kinesis-aggregation \
kubernetes \
kubernetes_metadata_filter \
ltsv-parser \
mongo \
mongo-slow-query \
mqtt-io \
multi-format-parser \
mysql \
mysql-query \
mysql-replicator \
newsyslog \
norikra \
parser \
pghstore \
ping-message \
rds-log \
rds-slowlog \
record-modifier \
record-reformer \
redshift \
referer-parser \
retag \
rewrite-tag-filter \
s3 \
script \
sns \
splunkapi \
sqs \
sqs-poll \
statsd \
sumologic-cloud-syslog \
sumologic_output \
td \
time_parser \
twilio \
ua-parser \
viaq_data_model \
webhdfs \
woothee \
zabbix \
zabbix-simple-bufferd \
"

RUN set -ex; \
   sed -r -i -e 's! main! main contrib non-free!g' /etc/apt/sources.list; \
   cat /etc/apt/sources.list ; \
   apt-get update -q; \
   apt-cache search '.*mysql.*-dev' ; \
   apt-get install -qy --no-install-recommends $BUILD_DEPS; \
   for name in $PLUGINS; do gem install "fluent-plugin-$name"; done; \
   gem sources --clear-all; \
   apt-get purge -qy $(dpkg-query --show --showformat '${Package}\n' '*-dev'); \
   rm -rf /var/lib/apt/lists/* /home/fluent/.gem/ruby/*/cache/*.gem
